# Generated by Django 6.0.5 on 2026-09-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreuveCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='preuves_clientes/')),
                ('nom_affiche', models.CharField(blank=True, max_length=100)),
                ('temoignage', models.TextField(blank=True)),
                ('consentement_obtenu', models.BooleanField(default=False)),
                ('publie', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', '-id'],
            },
        ),
    ]
