# Generated by Django 6.0.5 on 2026-09-22 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0003_avisproduit_jaimeproduit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_note',
            field=models.TextField(blank=True, default='', verbose_name='Note de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('NOT_SHIPPED', 'Non expédiée'), ('PREPARING', 'En préparation'), ('SHIPPED', 'Expédiée'), ('IN_TRANSIT', 'En transit'), ('DELIVERED', 'Livrée'), ('RETURNED', 'Retournée'), ('CANCELLED', 'Livraison annulée')], default='NOT_SHIPPED', max_length=30, verbose_name='Statut de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_reminder',
            field=models.BooleanField(default=False, verbose_name='Rappel activé'),
        ),
        migrations.AddField(
            model_name='order',
            name='reminder_note',
            field=models.TextField(blank=True, default='', verbose_name='Note de rappel'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date d’expédition'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(blank=True, choices=[('CANADA_POST', 'Postes Canada'), ('PUROLATOR', 'Purolator'), ('FEDEX', 'FedEx'), ('UPS', 'UPS'), ('DHL', 'DHL'), ('LOCAL', 'Livraison locale'), ('PICKUP', 'Récupération sur place'), ('OTHER', 'Autre')], default='', max_length=30, verbose_name='Service de livraison'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Numéro de suivi'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adresse',
            field=models.TextField(verbose_name='Adresse de livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse courriel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='indicatif',
            field=models.CharField(default='+1', max_length=10, verbose_name='Indicatif'),
        ),
        migrations.AlterField(
            model_name='order',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Non payé'), ('PENDING', 'Paiement en attente'), ('PAID', 'Payé'), ('FAILED', 'Paiement échoué'), ('REFUNDED', 'Remboursé')], default='UNPAID', max_length=20, verbose_name='Statut du paiement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pays',
            field=models.CharField(default='Canada', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payée'), ('PROCESSING', 'En traitement'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut de la commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Identifiant Stripe'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente ou client'),
        ),
    ]
