# Generated by Django 6.0.5 on 2026-09-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grace', '0004_alter_order_options_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
